### ISSUE TITLE
Each disease name/heading on the home page should link to the corresponding disease page.

### ISSUE THREAD

**Issue by osioke** [devcenter-square/disease-info-ui#20]
Each disease name/heading on the home page should link to disease page the way the `more` button links there

**Comment by yomete** [comment]
Fixed this in my last commit. I'll push to live.

**Comment by yomete** [comment]
Fixed @osioke

**Comment by osioke** [comment]
@yomete hope you signed up for [hacktoberfest](hacktoberfest.digitalocean.com) before the PR 😉
