### ISSUE TITLE
Sub-headings for diseases should be links, so they can hyperlinked to; like Symptoms or Diagnosis of Tuberculosis.

### ISSUE THREAD

**Issue by osioke** [devcenter-square/disease-info-ui#21]
Sections or Sub-headings for diseases should be links, so people can link or go directly to each section or sub-heading. Like `Symptoms` or `Diagnosis of Tuberculosis`.

Fixing this will allow access to specific information for disease like Symptoms of Tuberculosis - <https://disease-info.herokuapp.com/tuberculosis%20-%20WHO/symptoms> or Description on Lassa Fever - <https://disease-info.herokuapp.com/lassa%20fever%20-%20WHO/overview>. These links are examples and are currently not working.

**Comment by yomete** [comment]
Fixed by @mykeels PR #53 
Nice one man! Looking nice
