### ISSUE TITLE
Create a CONTRIBUTING.md file

### ISSUE THREAD

**Issue by osioke** [devcenter-square/disease-info-ui#25]
Create a CONTRIBUTING.md file to capture the steps a new contributor should go through to start his/her contribution to this project.

It should also mention the issues page and the project page.

Creating this file will allow GitHub direct a new repo visitor to this file so they know how and what they can do to contribute.

**Comment by wesleycsj** [comment]
I'll take this!

**Comment by osioke** [comment]
Wow, cool 👍👍

**Comment by wesleycsj** [comment]
I just need more detais about what can i put in the file...

**Comment by yomete** [comment]
This issue has been fixed by @AlexanderEllis PR

**Comment by osioke** [comment]
#43 fixed this.. Thanks @yomete & @wesleycsj
