### ISSUE TITLE
Adjust the PWA to automatically add data from any approved new scrapper into current disease structure.

### ISSUE THREAD

**Issue by osioke** [devcenter-square/disease-info-ui#26]
Adjust the PWA to automatically add data from any approved new scrapper into current disease structure. So that when more data for Tuberculosis is scrapped from another source, it is automatically added to the Tuberculosis view.

**Comment by yomete** [comment]
The PWA works by pulling data from the backend API and displaying it. Nothing more. 

So if the backend API added another scraper, as long as that new scraper is built into the API endpoint, its going to display.

**Comment by osioke** [comment]
Sorry @yomete, this issue is a duplicate of #24, I've edited the original to better explain what I meant.
