### ISSUE TITLE
wildcard searches not working

### ISSUE THREAD

**Issue by AfolabiOlaoluwa** [devcenter-square/disease-info-ui#32]
From the search, I should be able to search just an alphabet and the app will populate anything with that alphabet based on Disease Title/Name pattern. 

I searched AIDS and got no result, and when I search HIV/AIDS, I get something.

**Comment by mykeels** [comment]
Hasn't this been fixed?

**Comment by AfolabiOlaoluwa** [comment]
Oh, right. Fixed already.
