### ISSUE TITLE
Directives JavaScript URL returns HTML 

### ISSUE THREAD

**Issue by mykeels** [devcenter-square/disease-info-ui#47]
https://disease-info.herokuapp.com/assets/js/directives/directives.js

The above link should return a JavaScript document, however it returns almost the same HTML as the front-end UI https://disease-info.herokuapp.com/

**Comment by rectius** [comment]
The file you reported doesn't exist.  You're getting the html because your are not catching 404 errors.

**Comment by juancuiule** [comment]
Even the directives folder doesn't exist...

**Comment by yomete** [comment]
Fixed by Issue #48
