### ISSUE TITLE
Disease Description is in an Array

### ISSUE THREAD

**Issue by segun-adeleye** [devcenter-square/disease-info-ui#56]
On the landing page, the description for each disease is in an array. This is what it looks like

["Rabies is a vaccine-preventable viral disease which occurs in more than 150 countries and territories.","Dogs are the source of the vast majority of human rabies deaths, contributing up to 99% of all rabies transmissions to humans.","Rabies elimination is feasible by vaccinating dogs.","Infection causes tens of thousands of deaths every year, mostly in Asia and Africa.","40% of people who are bitten by suspect rabid animals are children under 15 years of age.","Immediate wound cleansing with soap and water after contact with a suspect rabid animal can be life-saving.","Every year, more than 15 million people worldwide receive a post-bite vaccination. This is estimated to prevent hundreds of thousands of rabies deaths annually."]

I guess the response from the API was put on the view as is. It needs to be formatted.

**Comment by yomete** [comment]
Thanks for this. I'll have a look at it today

**Comment by AfolabiOlaoluwa** [comment]
I think you can stripe it off on this UI. The API, injects []. 

For more clarity, the `facts method for the scraper` factored result with the injection of []` and it looks like this...

`result = lists.inject([]) .....`  

At the UI end, you can strip it off.

**Comment by yomete** [comment]
Yeah. That's the plan. 
I actually forgot about this 😭. @segun-adeleye if you could submit a PR with a fix, that would be awesome!

**Comment by segun-adeleye** [comment]
I will be delighted to. Will get on it ASAP. First Open Source PR on the way 🚀

**Comment by yomete** [comment]
Whoop!

**Comment by osioke** [comment]
Super cool @segun-adeleye looking forward to it :smiley:

**Comment by segun-adeleye** [comment]
I can see that `facts` is an array which means there can be more than one item in it. I will like to know what each item represents...a paragraph or what?

**Comment by segun-adeleye** [comment]
Fixed with PR https://github.com/devcenter-square/disease-info-ui/pull/57
